version: '3.8'

services:
  redis:
    image: redis/redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"

  api-gateway:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
